name: Publish
permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  publish_on_mac:
    timeout-minutes: 15 # Prevent stuck jobs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: install dependencies
        run: npm install

      - name: create_test_app
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make
      - uses: actions/upload-artifact@v4
        with:
          path: ./out
          retention-days: 1
          overwrite: true
